import logger from "../utils/logger";

/**
 * Pluggable transport for the OTP code generated by `otpService`.
 *
 * This is the *only* module that needs to change when wiring real email.
 * Drop in an `smtpOtpDelivery` (or `sesOtpDelivery`, etc.) implementing
 * the same interface and replace `container.otpDelivery` — every other
 * call site stays untouched.
 */

export interface OtpDeliveryArgs {
    userId: string;
    username: string;
    email: string;
    code: string;
    action: string;
    expiresAt: Date;
}

export interface OtpDeliveryProvider {
    /** Hint surfaced to the client so the UI can show "check your email" / "stub mode" appropriately. */
    readonly id: "stub" | "smtp" | "ses" | string;
    send(args: OtpDeliveryArgs): Promise<void>;
}

/**
 * Stub provider — logs the code at INFO so devs running the server can
 * read it from the console. Never use in production: real email is the
 * whole point of OTP.
 *
 * The stub deliberately does NOT use `redact.ts` for its own log line —
 * the purpose of the stub is to surface the plaintext to the developer.
 * The general redactor still scrubs `code` everywhere else (audit
 * payloads, route traces) so this is the single intentional plaintext
 * sink.
 */
export const stubOtpDelivery: OtpDeliveryProvider = {
    id: "stub",
    async send(args) {
        logger.info(
            `[OTP STUB] action=${args.action} user=${args.username} email=${args.email} ` +
                `code=${args.code} expires=${args.expiresAt.toISOString()}`
        );
    },
};
